from src import utils

EXTRA_DATA = {
    "intro": {
        "areaImage": utils.media_wrapper("areas/intro/intro.webp"),
        "areaLogoImage": utils.media_wrapper('areas/intro/intro_logo.svg'),
        "areaTitle": '序章',
        "areaSubtitle": '第零日',
        "bgFocusPositionX": 5,
        "bgFocusPositionY": 0,
        "subColor": "hsl(321.82, 73.33%, 94.12%)",
        "mainColor": "hsl(220.85, 85.45%, 67.65%)",
    },
    "day1": {
        "areaImage": utils.media_wrapper("areas/day1/day1.webp"),
        "areaLogoImage": utils.media_wrapper('areas/day1/logo_day1.svg'),
        "areaTitle": '素青',
        "areaSubtitle": '第一日',
        "bgFocusPositionX": 5,
        "bgFocusPositionY": 0,
        "subColor": "hsl(321.82, 73.33%, 94.12%)",
        "mainColor": "hsl(220.85, 85.45%, 67.65%)",
    },
    "day2": {
        "areaImage": utils.media_wrapper("areas/day2/day2.webp"),
        "areaLogoImage": utils.media_wrapper('areas/day2/logo_day2.svg'),
        "areaTitle": '秋蝉',
        "areaSubtitle": '第二日',
        "bgFocusPositionX": 5,
        "bgFocusPositionY": 0,
        "subColor": "hsl(57.69, 72.22%, 71.76%)",
        "mainColor": "hsl(176.3, 91.5%, 41.4%)",
    },
    "day3": {
        "areaImage": utils.media_wrapper("areas/day3/day3.webp"),
        "areaLogoImage": utils.media_wrapper('areas/day3/logo_day3.svg'),
        "areaTitle": '临水',
        "areaSubtitle": '第三日',
        "bgFocusPositionX": 5,
        "bgFocusPositionY": 0,
        "subColor": "hsl(195, 96.55%, 77.25%)",
        "mainColor": "hsl(242.18, 93.22%, 65.29%)",
    }
}

AREA_LIST = [
    {
        "bgUrl": utils.media_wrapper("areas/intro/intro.webp"),
        "title": "P&KU 3",
        "subtitle": "不妨临别前\n绘尽月色如霜",
        "buttonText": "前往探索",
        "buttonLink": "/about/introduction",
        "align": "right",
        "bottomPercentage": 17,
        "rightPercentage": 10,
        "bgFocusPositionX": 30,
        "bgFocusPositionY": 50,
        "mainColor": "#AAFAF9",
        "subColor": "#F4BCFC",
    },
    {
        "bgUrl": utils.media_wrapper("areas/intro/intro.webp"),
        "title": "P&KU 3",
        "subtitle": "不妨临别前\n绘尽月色如霜",
        "buttonText": "前往组队",
        "buttonLink": "/user/team",
        "align": "right",
        "bottomPercentage": 17,
        "rightPercentage": 10,
        "bgFocusPositionX": 30,
        "bgFocusPositionY": 50,
        "mainColor": "#AAFAF9",
        "subColor": "#F4BCFC",
    },
    {
        "bgUrl": utils.media_wrapper("areas/intro/intro.webp"),
        "title": "P&KU 3",
        "subtitle": "不妨临别前\n绘尽月色如霜",
        "buttonText": "前往序章",
        "buttonLink": "/area?dst=intro",
        "align": "right",
        "bottomPercentage": 17,
        "rightPercentage": 10,
        "bgFocusPositionX": 30,
        "bgFocusPositionY": 50,
        "mainColor": "#AAFAF9",
        "subColor": "#F4BCFC",
    },
    {
        "bgUrl": utils.media_wrapper("areas/day1/day1.webp"),
        "title": "第一日",
        "subtitle": "执意以火\n将画吻遍",
        "buttonText": "前往探索",
        "buttonLink": "/area?dst=day1",
        "align": "right",
        "bottomPercentage": 17,
        "rightPercentage": 10,
        "bgFocusPositionX": 20,
        "bgFocusPositionY": 20,
        "subColor": "hsl(321.82, 73.33%, 94.12%)",
        "mainColor": "hsl(220.85, 85.45%, 67.65%)",
    },
    {
        "bgUrl": utils.media_wrapper("areas/day2/day2.webp"),
        "title": "第二日",
        "subtitle": "重新许下\n生的祈愿",
        "buttonText": "前往探索",
        "buttonLink": "/area?dst=day2",
        "align": "right",
        "bottomPercentage": 17,
        "rightPercentage": 10,
        "bgFocusPositionX": 17,
        "bgFocusPositionY": 20,
        "subColor": "hsl(57.69, 72.22%, 71.76%)",
        "mainColor": "hsl(176.49, 90.59%, 66.67%)",
    },
    {
        "bgUrl": utils.media_wrapper("areas/day3/day3.webp"),
        "title": "第三日",
        "subtitle": "对平地\n绽出的水面",
        "buttonText": "前往探索",
        "buttonLink": "/area?dst=day3",
        "align": "right",
        "bottomPercentage": 17,
        "rightPercentage": 10,
        "bgFocusPositionX": 17,
        "bgFocusPositionY": 20,
        "subColor": "hsl(195, 96.55%, 77.25%)",
        "mainColor": "hsl(242.18, 93.22%, 65.29%)",
    },
]
