# 修改自 https://github.com/ysenarath/plyvel-stubs/blob/main/plyvel-stubs/__init__.pyi
from __future__ import annotations

from collections.abc import Iterator
from typing import Any

class WriteBatch:
    def put(self, key: bytes, value: bytes) -> None: ...
    def delete(self, key: bytes) -> None: ...
    def clear(self) -> None: ...
    def write(self) -> None: ...
    def __enter__(self) -> WriteBatch: ...
    def __exit__(
        self,
        exc_type: type | None,
        exc_value: BaseException | None,
        traceback: Any | None,
    ) -> None: ...

class DB:
    def __init__(
        self,
        name: str,
        create_if_missing: bool = False,
        error_if_exists: bool = False,
        paranoid_checks: bool = False,
        compression: bool | None = None,
        write_buffer_size: int | None = None,
        max_open_files: int | None = None,
        lru_cache_size: int | None = None,
        bloom_filter_bits: int | None = None,
    ) -> None: ...
    def close(self) -> None: ...
    def get(self, key: bytes, default: bytes | None = None) -> bytes | None: ...
    def put(self, key: bytes, value: bytes, sync: bool = False) -> None: ...
    def delete(self, key: bytes, sync: bool = False) -> None: ...
    def iterator(
        self,
        start: bytes | None = None,
        stop: bytes | None = None,
        include_start: bool = True,
        include_stop: bool = False,
        reverse: bool = False,
    ) -> Iterator[tuple[bytes, bytes]]: ...
    def prefix_iterator(self, prefix: bytes) -> Iterator[tuple[bytes, bytes]]: ...
    def range_iterator(self, start: bytes | None, stop: bytes | None) -> Iterator[tuple[bytes, bytes]]: ...
    def compact_range(self, start: bytes | None = None, stop: bytes | None = None) -> None: ...
    def property(self, name: str) -> str | None: ...
    def __enter__(self) -> DB: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: Any | None,
    ) -> None: ...
    def write_batch(self, transaction: bool = False, sync: bool = False) -> WriteBatch: ...
    def prefixed_db(self, prefix: bytes) -> PrefixedDB: ...

class PrefixedDB:
    def __init__(self, prefix: bytes, db: DB) -> None: ...
    def get(self, key: bytes, default: bytes | None = None) -> bytes | None: ...
    def put(self, key: bytes, value: bytes, sync: bool = False) -> None: ...
    def delete(self, key: bytes, sync: bool = False) -> None: ...
    def write_batch(self, transaction: bool = False, sync: bool = False) -> WriteBatch: ...
    def iterator(
        self,
        start: bytes | None = None,
        stop: bytes | None = None,
        include_start: bool = True,
        include_stop: bool = False,
        reverse: bool = False,
    ) -> Iterator[tuple[bytes, bytes]]: ...
    def snapshot(self) -> PrefixedDB: ...
    def prefixed_db(self, prefix: bytes) -> PrefixedDB: ...
