import Icon from '@ant-design/icons';
import React from 'react';

import BatteryFull from './icons/battery-full.svg?react';
import Book from './icons/book.svg?react';
import Building from './icons/building.svg?react';
import Cat from './icons/cat.svg?react';
import CatPaw from './icons/catpaw.svg?react';
import EveryUser from './icons/every-user.svg?react';
import Eye from './icons/eyes.svg?react';
import Faq from './icons/faq.svg?react';
import Fish from './icons/fish.svg?react';
import History from './icons/history.svg?react';
import Home from './icons/home.svg?react';
import IdCard from './icons/id-card-h.svg?react';
import Instruction from './icons/instruction.svg?react';
import Introduction from './icons/introduction.svg?react';
import LeftCircle from './icons/left-circle.svg?react';
import Mail from './icons/mail.svg?react';
import MiaoPlaza from './icons/miao-plaza.svg?react';
import MiaoStrip from './icons/miao-strip.svg?react';
import People from './icons/people.svg?react';
import PnKU3Day3 from './icons/pnku3-day3-icon.svg?react';
import PuzzlePiece from './icons/puzzle-piece.svg?react';
import Ranking from './icons/ranking.svg?react';
import Round from './icons/round.svg?react';
import Search from './icons/search.svg?react';
import Signal from './icons/signal.svg?react';
import Text from './icons/text-content.svg?react';
import Time from './icons/time.svg?react';
import Hint from './icons/tips.svg?react';
import Tools from './icons/tools.svg?react';
import TreasureMap from './icons/treasure-map.svg?react';
import Vacation from './icons/vacation.svg?react';

type SvgIconProps = {
    rotate?: number;
    spin?: boolean;
    style?: React.CSSProperties;
};

export const MiaoStripIcon = (props: SvgIconProps) => <Icon component={MiaoStrip} {...props} />;
export const HintIcon = (props: SvgIconProps) => <Icon component={Hint} {...props} />;
export const HistoryIcon = (props: SvgIconProps) => <Icon component={History} {...props} />;
export const TextIcon = (props: SvgIconProps) => <Icon component={Text} {...props} />;
export const TimeIcon = (props: SvgIconProps) => <Icon component={Time} {...props} />;
export const PeopleIcon = (props: SvgIconProps) => <Icon component={People} {...props} />;
export const RankingIcon = (props: SvgIconProps) => <Icon component={Ranking} {...props} />;
export const CatIcon = (props: SvgIconProps) => <Icon component={Cat} {...props} />;
export const IdCardIcon = (props: SvgIconProps) => <Icon component={IdCard} {...props} />;
export const EveryUserIcon = (props: SvgIconProps) => <Icon component={EveryUser} {...props} />;
export const HomeIcon = (props: SvgIconProps) => <Icon component={Home} {...props} />;
export const PlazaIcon = (props: SvgIconProps) => <Icon component={MiaoPlaza} {...props} />;
export const IntroductionIcon = (props: SvgIconProps) => <Icon component={Introduction} {...props} />;
export const FaqIcon = (props: SvgIconProps) => <Icon component={Faq} {...props} />;
export const ToolsIcon = (props: SvgIconProps) => <Icon component={Tools} {...props} />;
export const CatPawIcon = (props: SvgIconProps) => <Icon component={CatPaw} {...props} />;
export const LeftCircleIcon = (props: SvgIconProps) => <Icon component={LeftCircle} {...props} />;
export const MailIcon = (props: SvgIconProps) => <Icon component={Mail} {...props} />;
export const TreasureMapIcon = (props: SvgIconProps) => <Icon component={TreasureMap} {...props} />;
export const SignalIcon = (props: SvgIconProps) => <Icon component={Signal} {...props} />;
export const BatteryFullIcon = (props: SvgIconProps) => <Icon component={BatteryFull} {...props} />;
export const FishIcon = (props: SvgIconProps) => <Icon component={Fish} {...props} />;
export const BuildingIcon = (props: SvgIconProps) => <Icon component={Building} {...props} />;
export const InstructionIcon = (props: SvgIconProps) => <Icon component={Instruction} {...props} />;
export const VacationIcon = (props: SvgIconProps) => <Icon component={Vacation} {...props} />;
export const BookIcon = (props: SvgIconProps) => <Icon component={Book} {...props} />;
export const PuzzlePieceIcon = (props: SvgIconProps) => <Icon component={PuzzlePiece} {...props} />;
export const RoundIcon = (props: SvgIconProps) => <Icon component={Round} {...props} />;
export const EyeIcon = (props: SvgIconProps) => <Icon component={Eye} {...props} />;
export const SearchIcon = (props: SvgIconProps) => <Icon component={Search} {...props} />;
export const PnKU3Day3Icon = (props: SvgIconProps) => <Icon component={PnKU3Day3} {...props} />;
