name: Check Backend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  check-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes in backend directory
        id: backend-check
        run: |
          git fetch origin main
          # Check if there are any changes in the backend directory
          if git diff --name-only origin/main | grep '^backend/'; then
            echo "backend directory has changes."
            echo "has_changes=true" >> $GITHUB_ENV
          else
            echo "No changes in backend directory."
            echo "has_changes=false" >> $GITHUB_ENV
          fi

      - name: Install poetry
        if: env.has_changes == 'true'
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        if: env.has_changes == 'true'
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install dependencies
        if: env.has_changes == 'true'
        run: poetry install
      
      - name: Copy custom.py and secret.py
        if: env.has_changes == 'true'
        run: |
          pwd
          cp src/custom.example.py src/custom.py
          cp src/secret.example.py src/secret.py 

      - name: Run mypy
        if: env.has_changes == 'true'
        run: |
          poetry run mypy
      
      - name: Run ruff
        if: env.has_changes == 'true'
        run: |
          poetry run ruff check
          poetry run ruff format --check


